### ISSUE TITLE
RFE - Required software versions js/tmos

### ISSUE THREAD

**Issue by DumpySquare** [f5devcentral/f5-icontrollx-dev-kit#2]
Being rather new to this, it would be nice to know what versions of software this is for.  Not just TMOS, but which version of js.  I'm told the version of node running on a bigip is rather dated.  With this versioning, I would also like to see a docker container to quickly deploy and start developing ilx as needed.

**Comment by DumpySquare** [comment]
As I continue research in this direction and thinking out loud, I'm guess it might just be easier to modify one of the existing containers to add this tool.  Something like:  https://hub.docker.com/r/f5devcentral/f5-do-container

I presume these containers are running the appropriate code versions for an ilx extension to be able to run on an f5 also.

**Comment by zinkem5** [comment]
We're currently looking at revamping this package.

This package has not been extensively tested running on BIG-IP, to my knowledge.

Currently, the intent of the tool is to provide convenience functions to avoid this:
https://clouddocs.f5.com/products/iapp/iapp-lx/tmos-13_1/icontrollx_pacakges/working_with_icontrollx_packages.html

I personally use it for iControl LX Extension development, managing RPMs on my development BIG-IP from my local development environment, which happens to be macOS. 

I think the package could use the following enhancements to meet the stated goals:

- [ ] publish to npm and Document Node versions supported by the code, as written, for each module version
- [ ] provide a mechanism for portability across node versions via a tool like babel
- [ ] example Dockerfile, or a 'docker run'able dockerhub image

**Comment by adam-f5** [comment]
Repository Archived
